"""delete users and tokens tables

Revision ID: 31ef16aa5401
Revises: 0f3a21f0768a
Create Date: 2025-11-23 13:16:02.682395

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "31ef16aa5401"
down_revision: Union[str, Sequence[str], None] = "0f3a21f0768a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("articles_user_id_fkey"), "articles", type_="foreignkey")
    op.drop_constraint(op.f("comments_user_id_fkey"), "comments", type_="foreignkey")
    op.drop_table("tokens")
    op.drop_table("users")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    op.create_table(
        "users",
        sa.Column("id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column(
            "username", sa.VARCHAR(length=50), autoincrement=False, nullable=False
        ),
        sa.Column("email", sa.VARCHAR(length=254), autoincrement=False, nullable=False),
        sa.Column(
            "password", sa.VARCHAR(length=128), autoincrement=False, nullable=False
        ),
        sa.Column(
            "biography", sa.VARCHAR(length=255), autoincrement=False, nullable=True
        ),
        sa.Column(
            "avatar_url", sa.VARCHAR(length=2048), autoincrement=False, nullable=True
        ),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("is_active", sa.BOOLEAN(), autoincrement=False, nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("users_pkey")),
        sa.UniqueConstraint(
            "email",
            name=op.f("users_email_key"),
            postgresql_include=[],
            postgresql_nulls_not_distinct=False,
        ),
        sa.UniqueConstraint(
            "username",
            name=op.f("users_username_key"),
            postgresql_include=[],
            postgresql_nulls_not_distinct=False,
        ),
    )
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(
        op.f("comments_user_id_fkey"), "comments", "users", ["user_id"], ["id"]
    )
    op.create_foreign_key(
        op.f("articles_user_id_fkey"), "articles", "users", ["user_id"], ["id"]
    )
    op.create_table(
        "tokens",
        sa.Column("jti", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("user_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "expires_at",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("is_revoked", sa.BOOLEAN(), autoincrement=False, nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("tokens_user_id_fkey")
        ),
        sa.PrimaryKeyConstraint("jti", name=op.f("tokens_pkey")),
    )

    # ### end Alembic commands ###
