"""delete article attr is_deleted

Revision ID: 60223af6ef6f
Revises: 8eb558d13794
Create Date: 2025-09-08 19:37:43.618938

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '60223af6ef6f'
down_revision: Union[str, Sequence[str], None] = '8eb558d13794'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('articles', 'is_deleted')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('articles', sa.Column('is_deleted', sa.BOOLEAN(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
