"""create articles relationship with users

Revision ID: 8eb558d13794
Revises: a0ec31f52727
Create Date: 2025-09-08 19:28:28.589898

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8eb558d13794'
down_revision: Union[str, Sequence[str], None] = 'a0ec31f52727'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('articles', sa.Column('user_id', sa.UUID(), nullable=False))
    op.create_foreign_key(None, 'articles', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'articles', type_='foreignkey')
    op.drop_column('articles', 'user_id')
    # ### end Alembic commands ###
