"""add optional params in user table

Revision ID: de23d5a28f57
Revises: 8e9725f0475b
Create Date: 2025-09-06 21:34:10.785061

"""

import uuid
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import table, column


# revision identifiers, used by Alembic.
revision: str = "de23d5a28f57"
down_revision: Union[str, Sequence[str], None] = "8e9725f0475b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("username", sa.String(length=50), nullable=True))

    users_table = table(
        "users",
        column("id", sa.UUID),
        column("email", sa.String),
        column("username", sa.String),
    )

    connection = op.get_bind()
    result = connection.execute(sa.select(users_table.c.id, users_table.c.email))
    for row in result:
        username = row.email.split("@")[0] + "_" + str(uuid.uuid4())[:8]
        connection.execute(
            users_table.update()
            .where(users_table.c.id == row.id)
            .values(username=username[:50])  # обрезаем до 50 символов
        )

    op.alter_column("users", "username", nullable=False)

    op.add_column("users", sa.Column("bio", sa.String(length=255), nullable=True))
    op.add_column(
        "users", sa.Column("image_url", sa.String(length=2048), nullable=True)
    )
    op.add_column(
        "users",
        sa.Column(
            "created_at", sa.DateTime(), nullable=False, server_default=sa.func.now()
        ),
    )
    op.add_column(
        "users",
        sa.Column("is_banned", sa.Boolean(), nullable=False, server_default="false"),
    )

    op.create_unique_constraint(op.f("users_username_key"), "users", ["username"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("users_username_key"), "users", type_="unique")

    # Удаляем колонки
    op.drop_column("users", "is_banned")
    op.drop_column("users", "created_at")
    op.drop_column("users", "image_url")
    op.drop_column("users", "bio")
    op.drop_column("users", "username")
    # ### end Alembic commands ###
