"""описание изменений

Revision ID: 4802b1d34aa9
Revises: eddc185c35c5
Create Date: 2025-12-08 09:57:33.033426

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4802b1d34aa9'
down_revision: Union[str, Sequence[str], None] = 'eddc185c35c5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('subsсription_key', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'subsсription_key')
    # ### end Alembic commands ###
